name: MAIN
on:
  workflow_dispatch:
  push:
    branches:
      - qa
      - dev
      - master
  pull_request:
      branches:
        - dev
        
permissions:
    checks: write
    security-events: write
    packages: write
    actions: write
    pull-requests: write
    
jobs:
    Talisman:
      name: Talisman
      uses: ./.github/workflows/talisman.yml
      secrets: inherit
      
    KICS:
      needs: Talisman
      name: KICS
      uses: ./.github/workflows/KICS.yml
      secrets: inherit 

    Build_Test:
      needs: KICS
      name: Build and Test
      uses: ./.github/workflows/Build_Test.yml
      secrets: inherit
    
    Snyk:
      needs: Build_Test
      name: Snyk_security check
      uses: ./.github/workflows/snyk.yml
      secrets: inherit
     
    Sbom:
      needs: Snyk
      name: Sbom
      uses: ./.github/workflows/sbom.yml
      secrets: inherit

    Docker_build:
      needs: Sbom
      name: Docker build
      uses: ./.github/workflows/docker.yml
      secrets: inherit
      
    Deployment:
      needs: Docker_build
      name: Deployment
      uses: ./.github/workflows/deploy.yml
      secrets: inherit
      
    Deploy:
      runs-on: ubuntu-latest
      needs: Deployment 
      steps:
       - name: Install Kubectl
         uses: azure/setup-kubectl@v3
         with:
          version: 'v1.28.0' # default is latest stable
         id: install
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-west-2
       - name: Set kubectl context
         run: aws eks --region us-west-2 update-kubeconfig --name ekscluster
       - name: Checkout Repository
         uses: actions/checkout@v3
         with:
            repository: GKprojects/deployment   
            token: ${{ secrets.PAT_TOKEN }}
       - name: Apply Kubernetes manifests
         run: |
          cd ${{ github.event.repository.name }}
          kubectl apply -f deployment.yaml -f service.yml
